[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
ffi = true
fs_permissions = [{ access = "read-write", path = "../shared" }]

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 256
depth = 50
fail_on_revert = false

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
